// Live visitor geo-data from Vercel Analytics (visits per country).
export interface CountryStat {
  flag: string;
  name: string;
  visits: number;
}

export const COUNTRIES: CountryStat[] = [
  { flag: "🇮🇳", name: "India", visits: 6100 },
  { flag: "🇺🇸", name: "United States of America", visits: 515 },
  { flag: "🇮🇩", name: "Indonesia", visits: 162 },
  { flag: "🇳🇵", name: "Nepal", visits: 132 },
  { flag: "🇬🇧", name: "United Kingdom", visits: 119 },
  { flag: "🇳🇬", name: "Nigeria", visits: 106 },
  { flag: "🇨🇦", name: "Canada", visits: 99 },
  { flag: "🇵🇭", name: "Philippines", visits: 86 },
  { flag: "🇩🇪", name: "Germany", visits: 84 },
  { flag: "🇦🇺", name: "Australia", visits: 73 },
  { flag: "🇫🇷", name: "France", visits: 71 },
  { flag: "🇰🇪", name: "Kenya", visits: 67 },
  { flag: "🇹🇷", name: "Türkiye", visits: 64 },
  { flag: "🇸🇬", name: "Singapore", visits: 61 },
  { flag: "🇦🇪", name: "United Arab Emirates", visits: 60 },
  { flag: "🇲🇾", name: "Malaysia", visits: 60 },
  { flag: "🇪🇸", name: "Spain", visits: 57 },
  { flag: "🇳🇱", name: "Netherlands", visits: 51 },
  { flag: "🇧🇩", name: "Bangladesh", visits: 49 },
  { flag: "🇧🇷", name: "Brazil", visits: 45 },
  { flag: "🇬🇭", name: "Ghana", visits: 33 },
  { flag: "🇿🇦", name: "South Africa", visits: 29 },
  { flag: "🇵🇱", name: "Poland", visits: 27 },
  { flag: "🇻🇳", name: "Vietnam", visits: 27 },
  { flag: "🇵🇰", name: "Pakistan", visits: 26 },
  { flag: "🇸🇦", name: "Saudi Arabia", visits: 26 },
  { flag: "🇯🇵", name: "Japan", visits: 24 },
  { flag: "🇮🇹", name: "Italy", visits: 22 },
  { flag: "🇹🇭", name: "Thailand", visits: 21 },
  { flag: "🇱🇰", name: "Sri Lanka", visits: 20 },
  { flag: "🇲🇽", name: "Mexico", visits: 20 },
  { flag: "🇮🇪", name: "Ireland", visits: 17 },
  { flag: "🇷🇴", name: "Romania", visits: 17 },
  { flag: "🇸🇪", name: "Sweden", visits: 17 },
  { flag: "🇪🇬", name: "Egypt", visits: 16 },
  { flag: "🇲🇦", name: "Morocco", visits: 16 },
  { flag: "🇦🇷", name: "Argentina", visits: 14 },
  { flag: "🇮🇱", name: "Israel", visits: 13 },
  { flag: "🇨🇿", name: "Czech Republic", visits: 12 },
  { flag: "🇳🇿", name: "New Zealand", visits: 12 },
  { flag: "🇪🇹", name: "Ethiopia", visits: 11 },
  { flag: "🇳🇴", name: "Norway", visits: 10 },
  { flag: "🇨🇭", name: "Switzerland", visits: 9 },
  { flag: "🇫🇮", name: "Finland", visits: 9 },
  { flag: "🇲🇻", name: "Maldives", visits: 9 },
  { flag: "🇧🇪", name: "Belgium", visits: 7 },
  { flag: "🇩🇿", name: "Algeria", visits: 7 },
  { flag: "🇶🇦", name: "Qatar", visits: 7 },
  { flag: "🇷🇸", name: "Serbia", visits: 7 },
  { flag: "🇷🇼", name: "Rwanda", visits: 7 },
  { flag: "🇩🇰", name: "Denmark", visits: 6 },
  { flag: "🇬🇪", name: "Georgia", visits: 6 },
  { flag: "🇰🇷", name: "South Korea", visits: 6 },
  { flag: "🇸🇰", name: "Slovakia", visits: 6 },
  { flag: "🇺🇬", name: "Uganda", visits: 6 },
  { flag: "🇺🇿", name: "Uzbekistan", visits: 6 },
  { flag: "🇨🇴", name: "Colombia", visits: 5 },
  { flag: "🇰🇭", name: "Cambodia", visits: 5 },
  { flag: "🇵🇹", name: "Portugal", visits: 5 },
  { flag: "🇹🇳", name: "Tunisia", visits: 5 },
  { flag: "🇹🇼", name: "Taiwan", visits: 5 },
  { flag: "🇧🇬", name: "Bulgaria", visits: 4 },
  { flag: "🇪🇪", name: "Estonia", visits: 4 },
  { flag: "🇭🇺", name: "Hungary", visits: 4 },
  { flag: "🇮🇶", name: "Iraq", visits: 4 },
  { flag: "🇯🇴", name: "Jordan", visits: 4 },
  { flag: "🇱🇹", name: "Lithuania", visits: 4 },
  { flag: "🇴🇲", name: "Oman", visits: 4 },
  { flag: "🇸🇳", name: "Senegal", visits: 4 },
  { flag: "🇦🇹", name: "Austria", visits: 3 },
  { flag: "🇬🇷", name: "Greece", visits: 3 },
  { flag: "🇭🇰", name: "Hong Kong", visits: 3 },
  { flag: "🇰🇿", name: "Kazakhstan", visits: 3 },
  { flag: "🇱🇷", name: "Liberia", visits: 3 },
  { flag: "🇲🇩", name: "Moldova", visits: 3 },
  { flag: "🇵🇪", name: "Peru", visits: 3 },
  { flag: "🇿🇼", name: "Zimbabwe", visits: 3 },
  { flag: "🇦🇿", name: "Azerbaijan", visits: 2 },
  { flag: "🇨🇷", name: "Costa Rica", visits: 2 },
  { flag: "🇩🇴", name: "Dominican Republic", visits: 2 },
  { flag: "🇬🇬", name: "Guernsey", visits: 2 },
  { flag: "🇰🇼", name: "Kuwait", visits: 2 },
  { flag: "🇲🇴", name: "Macao", visits: 2 },
  { flag: "🇲🇺", name: "Mauritius", visits: 2 },
  { flag: "🇲🇿", name: "Mozambique", visits: 2 },
  { flag: "🇳🇮", name: "Nicaragua", visits: 2 },
  { flag: "🇵🇷", name: "Puerto Rico", visits: 2 },
  { flag: "🇽🇰", name: "Kosovo", visits: 2 },
  { flag: "🇦🇩", name: "Andorra", visits: 1 },
  { flag: "🇦🇫", name: "Afghanistan", visits: 1 },
  { flag: "🇧🇦", name: "Bosnia and Herzegovina", visits: 1 },
  { flag: "🇧🇭", name: "Bahrain", visits: 1 },
  { flag: "🇧🇯", name: "Benin", visits: 1 },
  { flag: "🇧🇹", name: "Bhutan", visits: 1 },
  { flag: "🇨🇮", name: "Côte d'Ivoire", visits: 1 },
  { flag: "🇨🇱", name: "Chile", visits: 1 },
  { flag: "🇨🇲", name: "Cameroon", visits: 1 },
  { flag: "🇨🇾", name: "Cyprus", visits: 1 },
  { flag: "🇬🇹", name: "Guatemala", visits: 1 },
  { flag: "🇬🇾", name: "Guyana", visits: 1 },
  { flag: "🇮🇸", name: "Iceland", visits: 1 },
  { flag: "🇯🇲", name: "Jamaica", visits: 1 },
  { flag: "🇰🇬", name: "Kyrgyzstan", visits: 1 },
  { flag: "🇱🇧", name: "Lebanon", visits: 1 },
  { flag: "🇱🇺", name: "Luxembourg", visits: 1 },
  { flag: "🇲🇰", name: "North Macedonia", visits: 1 },
  { flag: "🇲🇳", name: "Mongolia", visits: 1 },
  { flag: "🇵🇸", name: "State of Palestine", visits: 1 },
  { flag: "🇷🇺", name: "Russia", visits: 1 },
  { flag: "🇸🇾", name: "Syria", visits: 1 },
  { flag: "🇹🇿", name: "Tanzania", visits: 1 },
  { flag: "🇺🇦", name: "Ukraine", visits: 1 },
  { flag: "🇻🇪", name: "Venezuela", visits: 1 },
];

export const COUNTRY_COUNT = COUNTRIES.length;

export function formatVisitors(n: number): string {
  if (n >= 1000) {
    const k = (n / 1000).toFixed(1).replace(/\.0$/, "");
    return `${k}K`;
  }
  return String(n);
}